# Generated by Django 4.1.7 on 2023-03-06 04:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0002_tag_invoice_tag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='tag',
            new_name='tags',
        ),
    ]
